# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
from django.utils import timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey('blog_part.Post', related_name='comments')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
            ],
        ),
         migrations.CreateModel(
            name='Resume',
            fields=[
                ('img', models.ImageField("Photo", upload_to='images/', help_text='')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField()),
                ('phone', models.CharField(max_length=13)),
                ('about', models.TextField()),
                ('objective', models.TextField()),
                ('languages', models.TextField()),
                ('it_skill_set', models.TextField()),
            ],
        ),
        
    ]
